### ISSUE TITLE
Weird id returned for lists

### ISSUE THREAD

**Issue by nanocreaator** [mongoosejs/mongoose-lean-id#3]
Hello!

First of all thanks for the lib!
However, I noticed a weird behavior when using mongoose-lean-id with a list of objectids.
Below is a code sample to represent what is happening.
If you want to see on live, here it is:
[codesandbox](https://codesandbox.io/s/4jjk7y76n0) (needs change dbs confs).

Everything works fine except when I have a **list** of objectIDs defined in my schema.
Ex.:

```
let MySchema = new mongoose.Schema({
  name: String,
  some_ids: [{
      type: mongoose.Schema.Types.ObjectId,
      ref: "Somethinging"
    }]
});
```
**mongoose-lean-id** add in my final object the id (copy of _id) as expected but it changes all object_ids in the array for a weird number.

This is the answer **without** your lib and using _.lean()_:

- [OK ] 

```
{ _id: 5c6a8333df1d5e01bb1f5558,
  name: 'Blablabla',
  some_ids:
   [ 5c6a859b3e044000000ecd09, 5c6a8333df1d5e01bb1f5558 ],
  __v: 0
}
```

This is the answer **with** your lib and using _.lean()_:

- [NOT OK ] 

```
{ _id: 5c6a8333df1d5e01bb1f5558,
  name: 'Blablabla',
  some_ids: [ 356336613835396233653034343030303030306563643039, 
              356336613833333364663164356530316262316635353538 ],
  __v: 0,
  id: '5c6a8333df1d5e01bb1f5558'
}
```

Maybe this behavior is expected somehow as well and I am missing something. If is the case, sorry for the report.

B.R.

**Comment by vkarpov15** [comment]
Published 0.2.0 with the fix, this lib will ignore ObjectId arrays now :+1:
